Repository iron-fish/ironfish, pull requests merged in 2024-06, with the labels that each got.

#5018 Remove Wallet.getLatestHeadHash()
  ironfish-cli/src/commands/chain/rewind.ts
  ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
  ironfish/src/wallet/wallet.test.ts
  ironfish/src/wallet/wallet.ts
Labels: breaking-change-sdk

#5039 Automatically start the worker pool if a job is submitted
  ironfish/src/testUtilities/nodeTest.ts
  ironfish/src/workerPool/pool.ts
Labels: perf-improvement

#5041 Improve the calculation for the number of workers in the worker pool
  Cargo.lock
  ironfish-rust-nodejs/Cargo.toml
  ironfish-rust-nodejs/index.d.ts
  ironfish-rust-nodejs/index.js
  ironfish-rust-nodejs/src/lib.rs
  ironfish/src/fileStores/config.ts
  ironfish/src/workerPool/pool.ts
  supply-chain/audits.toml
  supply-chain/imports.lock
Labels: perf-improvement

#5048 Change `DecryptNotesRequest` to require a common list of accounts and options
  ironfish/src/rpc/routes/wallet/utils.ts
  ironfish/src/wallet/wallet.ts
  ironfish/src/workerPool/pool.ts
  ironfish/src/workerPool/tasks/decryptNotes.test.ts
  ironfish/src/workerPool/tasks/decryptNotes.ts
Labels: breaking-change-sdk, perf-improvement

#5049 Change `DecryptNotesResponse` to use a sparse serialization format
  ironfish/src/workerPool/tasks/decryptNotes.ts
Labels: perf-improvement

#5063 Have WalletScanner use chain directly if available
  ironfish/src/node.ts
  ironfish/src/wallet/scanner/chainProcessorWithTransactions.ts
  ironfish/src/wallet/scanner/walletScanner.ts
  ironfish/src/wallet/wallet.test.ts
  ironfish/src/wallet/wallet.ts
Labels: perf-improvement

#5058 Maximize decryption parallelism during wallet scans
  ironfish/src/fileStores/config.ts
  ironfish/src/utils/asyncQueue.test.ts
  ironfish/src/utils/asyncQueue.ts
  ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
  ironfish/src/wallet/scanner/__fixtures__/noteDecryptor.test.ts.fixture
  ironfish/src/wallet/scanner/__fixtures__/walletScanner.test.ts.fixture
  ironfish/src/wallet/scanner/noteDecryptor.test.ts
  ironfish/src/wallet/scanner/noteDecryptor.ts
  ironfish/src/wallet/scanner/walletScanner.test.ts
  ironfish/src/wallet/scanner/walletScanner.ts
  ironfish/src/wallet/wallet.test.ts
  ironfish/src/wallet/wallet.ts
  ironfish/src/workerPool/pool.ts
Labels: perf-improvement

#5075 Fast construction of `NoteEncrypted` during wallet scans
  ironfish-rust-nodejs/index.d.ts
  ironfish-rust-nodejs/src/structs/note_encrypted.rs
  ironfish-rust/src/merkle_note.rs
  ironfish-rust/src/serializing/mod.rs
  ironfish/src/primitives/noteEncrypted.ts
  ironfish/src/wallet/scanner/walletScanner.ts
  ironfish/src/workerPool/tasks/decryptNotes.test.ts
  ironfish/src/workerPool/tasks/decryptNotes.ts
Labels: perf-improvement
